manifest:
  remotes:
    - name: nuvoton
      url-base: https://github.com/Nuvoton-Israel/zephyr

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: zephyr
      remote: nuvoton
      path: zephyr
      revision: cf327357f28c63969a1ab01bdfb871cd6884f51c
      import: 
        name-allowlist:
          - cmsis
          - mcuboot

  self:
    path: openbic

